name: Build and Deploy

# on: の後のコロンとインデントを修正
on:
  push:
    # branches: の後のハイフンとスペースを修正
    branches:
      - main

# jobs: のインデントを修正
jobs:
  # ジョブ名とコロン、インデントを修正
  ftp_deploy_job:
    name: FTP Deploy Action
    # runs-on: のインデントを修正
    runs-on: ubuntu-latest
    
    # steps: のインデントを修正
    steps:
      # uses: のインデントを修正
      - uses: actions/checkout@v4 # 最新の v4 を推奨
      
      # name: のインデントを修正
      - name: FTP Deploy
        # uses: のインデントを修正
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0 # 最新の v4.3.0 を推奨
        
        # with: ブロックを使用して環境変数やパラメータを設定
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # local-dir: や remote-dir: の記述を修正
          local-dir: ./
          remote-dir: /2025/develop